Route Followed create
UdL-EPS-SoftArch/myroutes pull request #26
Opened 2023-12-14 15:52 UTC by SergiFn

2023-12-15 16:29 UTC, rogargon commented
Please, @SergiFn, update your branch to the last version of the main one (by merging the origin/main into your branch and then pushing the merge commit after checking that everything works as expected). Thanks.

2023-12-17 22:03 UTC, SergiFn commented
I already merged my branch to the main one and fixed all discrepancies and issues.

2023-12-18 11:33 UTC, rogargon requested changes

2023-12-18 11:33 UTC, rogargon commented on src/app/routeFollowed/routeFollowed.ts
> +  routeOrigin: Route;
The whole Route followed should not be serialised when doing the POST to create the RouteFollowed. As we did when testing the backend, just the Route URI as a string should be sent to the backend, because the Route already exists.

By the way, `routeOrigin` is used as the relationship between a followed route and the route, though in the Domain Model drawing it is labelled `follows`. Please, update the diagram accordingly or change the relationship name to `follows`. Whatever is right as both use the same terminology.

2023-12-19 14:29 UTC, rogargon commented on src/app/routeFollowed/routeFollowed.ts
> -  routeOrigin: Route;
You will also need to update it in the backend. And make it of type string, because you just need to send the URI of the Route when creating a RouteFollowed

2023-12-19 17:05 UTC, SergiFn commented on src/app/routeFollowed/routeFollowed.ts
> -  routeOrigin: Route;
I already submitted a pull request on the backend side fixing all the issues.

2023-12-21 15:14 UTC, rogargon approved these changes

2023-12-21 15:14 UTC, merged