Waypoint entity
UdL-EPS-SoftArch/myroutes pull request #28
Opened 2023-12-17 21:36 UTC by ZcR-01

2023-12-18 11:42 UTC, rogargon requested changes

2023-12-18 11:42 UTC, rogargon commented on src/app/app-routing.module.ts
> +import {WaypointCreateComponent} from "./waypoint/waypoint-create/waypoint-create.component";
It seems there is some code not yet committed. Compilation is failing here with error:
` Cannot find module './waypoint/waypoint-create/waypoint-create.component' or its corresponding type declarations.`

2023-12-23 20:05 UTC, rogargon commented on src/app/app-routing.module.ts
> +import {WaypointCreateComponent} from "./waypoint/waypoint-create/waypoint-create.component";
@ZcR-01, check the missing waypoint-create.component code

2023-12-24 10:08 UTC, ZcR-01 commented
I have uploaded the missing create and waypoint list files, the other parts of the component will be in another branch. Attach me a change request if something is wrong.

2023-12-24 12:21 UTC, rogargon approved these changes

2023-12-24 12:21 UTC, merged